### PR TITLE
Allow several countries to be set in product feed (will sync products for multiple countries)

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
Reverts PrestaShopCorp/psxmarketingwithgoogle#1023 that reverts https://github.com/PrestaShopCorp/psxmarketingwithgoogle/pull/1012

### CODE REVIEW

**Comment by AndrzejSzczepanik** [comment]
I have store multi countries, multilanguages and multi currecy with shipings rates devided by zones. One zone- one country.Will be any posibility to feed all countries with their local languag and currency.?? Currently I can export only to one country what have the same curency as main basic currency

**Comment by AndrzejSzczepanik** [comment]
Can I check new posiibilities?

**Comment by Quetzacoalt91** [comment]
This was not merged as the API responsible in synchronizing products is not ready yet. This will be made available for every one as soon as we are ready (In 1~2 months).

**Comment by AndrzejSzczepanik** [comment]
> This was not merged as the API responsible in synchronizing products is not ready yet. This will be made available for every one as soon as we are ready (In 1~2 months).

Everyone is waiting this functionality, without this metenance daily synchronisation in multilingual, multi countries & currencies stores is a nightmare.

**Comment by Quetzacoalt91** [comment]
We often discuss with the merchants to know what could be improved and that's why this topic is in the roadmap.

No need to push it though, this won't make it any faster as it is already planned. :slightly_smiling_face:

**Comment by AndrzejSzczepanik** [comment]
Hello, I just wanted to report a problem. Well, for local currencies - say, apart from USD, EUR, often the store, due to the volatility of exchange rates, is run with the main base currency as one of the listed ones and with automatic updating of the rates via the cron job. In such a situation, when exporting to Google Merchant, the local language is exported, the local currency is exported, e.g. PLN with values as for EUR, of course Google Merchant does not accept such products, can I get around it somehow?

**Pull request merged**
