### PR TITLE
Require at least version 1.7.7 of CloudSync

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Review by elisegriset92 — APPROVED** [review]

**Comment by xhums1** [comment]
how do you update eventbus?

**Comment by xhums1** [comment]
The version of the module PrestaShop EventBus running on this shop is older than the minimum required . You may use PrestaShop Marketing with Google but some features (i.e product synchronization) won't be available until you upgrade PrestaShop EventBus
can't update, please fix

**Comment by jorgerey89** [comment]
How can I update the "Prestashop EventBus" module to version 1.7.7? When I hit the update button in the "Marketing with Google" module itself, it doesn't do anything to update "Prestashop EventBus".

Can you fix it?

**Comment by Quetzacoalt91** [comment]
The message remains as the version was not available on the marketplace yet (their release was not complete). Try again in a few hours.

**Pull request merged**
